name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci
      - name: Build app
        run: |
          npm run build
          npm run dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: dist/
